server:
  port: '8765'
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: currency-conversion
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
