apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: shonsu/msrvc-currency-conversion-service:0.0.14-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: msrvc-currency-conversion-service
        env:
          - name: CURRENCY_EXCHANGE_URI
            value: http://currency-exchange
          - name: CURRENCY_EXCHANGE_PORT
            value: "8000"
      restartPolicy: Always
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer
