server:
  port: '8100'
spring:
  application:
    name: currency-conversion
#  config:
#    import: optional:configserver:http://localhost:8888
#  cloud:
#    openfeign:
#      micrometer:
#        enabled: false
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
app:
  exchangeServiceName: ${CURRENCY_EXCHANGE_URI:http://localhost}
  exchangeServicePort: ${CURRENCY_EXCHANGE_PORT:8000}