server:
  port: '8761'
spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:88888
eureka:
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
