server:
  port: '8000'
spring:
  application:
    name: currency-exchange
#  config:
#    import: optional:configserver:http://localhost:8888
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      sample-api:
        maxAttempts: 5
        waitDuration: 1s
        enable-exponential-backoff: true
#  circuitbreaker:
#    instances:
#      default:
#        failure-rate-threshold: 90
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 5
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

